/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package practica3;

import java.awt.Color;
import java.awt.Graphics;
import java.awt.Point;
import java.awt.event.MouseEvent;
import javax.sound.sampled.Line;

/**
 *
 * @author ivan
 */
public class VentanaPrincipal extends javax.swing.JFrame {

    /**
     * Creates new form VentanaPrincipal
     */
    public VentanaPrincipal() {
        initComponents();
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Boton = new javax.swing.JButton();
        Boton2 = new javax.swing.JButton();

        FormListener formListener = new FormListener();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        addMouseListener(formListener);
        addMouseMotionListener(formListener);
        getContentPane().setLayout(new java.awt.FlowLayout());

        Boton.setText("Boton");
        Boton.addMouseListener(formListener);
        Boton.addMouseMotionListener(formListener);
        Boton.addActionListener(formListener);
        getContentPane().add(Boton);

        Boton2.setText("Boton2");
        Boton2.addMouseListener(formListener);
        Boton2.addActionListener(formListener);
        getContentPane().add(Boton2);

        pack();
    }

    // Code for dispatching events from components to event handlers.

    private class FormListener implements java.awt.event.ActionListener, java.awt.event.MouseListener, java.awt.event.MouseMotionListener {
        FormListener() {}
        public void actionPerformed(java.awt.event.ActionEvent evt) {
            if (evt.getSource() == Boton) {
                VentanaPrincipal.this.BotonActionPerformed(evt);
            }
            else if (evt.getSource() == Boton2) {
                VentanaPrincipal.this.Boton2ActionPerformed(evt);
            }
        }

        public void mouseClicked(java.awt.event.MouseEvent evt) {
            if (evt.getSource() == VentanaPrincipal.this) {
                VentanaPrincipal.this.formMouseClicked(evt);
            }
            else if (evt.getSource() == Boton) {
                VentanaPrincipal.this.BotonMouseClicked(evt);
            }
            else if (evt.getSource() == Boton2) {
                VentanaPrincipal.this.Boton2MouseClicked(evt);
            }
        }

        public void mouseEntered(java.awt.event.MouseEvent evt) {
            if (evt.getSource() == VentanaPrincipal.this) {
                VentanaPrincipal.this.formMouseEntered(evt);
            }
            else if (evt.getSource() == Boton) {
                VentanaPrincipal.this.BotonMouseEntered(evt);
            }
        }

        public void mouseExited(java.awt.event.MouseEvent evt) {
            if (evt.getSource() == Boton) {
                VentanaPrincipal.this.BotonMouseExited(evt);
            }
        }

        public void mousePressed(java.awt.event.MouseEvent evt) {
            if (evt.getSource() == VentanaPrincipal.this) {
                VentanaPrincipal.this.formMousePressed(evt);
            }
        }

        public void mouseReleased(java.awt.event.MouseEvent evt) {
        }

        public void mouseDragged(java.awt.event.MouseEvent evt) {
            if (evt.getSource() == Boton) {
                VentanaPrincipal.this.BotonMouseDragged(evt);
            }
            else if (evt.getSource() == VentanaPrincipal.this) {
                VentanaPrincipal.this.formMouseDragged(evt);
            }
        }

        public void mouseMoved(java.awt.event.MouseEvent evt) {
            if (evt.getSource() == VentanaPrincipal.this) {
                VentanaPrincipal.this.formMouseMoved(evt);
            }
        }
    }// </editor-fold>//GEN-END:initComponents

    private void BotonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BotonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_BotonActionPerformed

    private void BotonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_BotonMouseClicked
        this.Boton.setBackground(Color.red);
    }//GEN-LAST:event_BotonMouseClicked

    private void BotonMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_BotonMouseEntered
        this.Boton.setBackground(Color.BLUE);
    }//GEN-LAST:event_BotonMouseEntered

    private void BotonMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_BotonMouseExited
        this.Boton.setBackground(Color.GREEN);
    }//GEN-LAST:event_BotonMouseExited

    private void BotonMouseDragged(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_BotonMouseDragged
        this.Boton.setBackground(Color.LIGHT_GRAY);
    }//GEN-LAST:event_BotonMouseDragged

    private void formMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_formMouseClicked
 
    }//GEN-LAST:event_formMouseClicked

    private void Boton2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Boton2MouseClicked
         this.setBackground(Color.MAGENTA);
    }//GEN-LAST:event_Boton2MouseClicked

    private void Boton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Boton2ActionPerformed
        this.Boton2.setBackground(Color.ORANGE);
    }//GEN-LAST:event_Boton2ActionPerformed

    private void formMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_formMouseEntered

    }//GEN-LAST:event_formMouseEntered

    private void formMouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_formMouseMoved
        this.p.x = evt.getX();
        this.p.y = evt.getY();
        this.Paint(this.getGraphics(), p);
    }//GEN-LAST:event_formMouseMoved

    private void formMouseDragged(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_formMouseDragged
        this.p_final = evt.getPoint();
        this.PaintLine(this.getGraphics(), p_inicial, p_final);
    }//GEN-LAST:event_formMouseDragged

    private void formMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_formMousePressed
        this.p_inicial = evt.getPoint();
    }//GEN-LAST:event_formMousePressed
    
    public void Paint(java.awt.Graphics g, Point p){
        super.paint(g);
        g.fillOval(p.x - 5, p.y - 5, 10, 10);
    }
    
    public void PaintLine(java.awt.Graphics g, Point p, Point q){
        super.paint(g);
        g.drawLine(p.x, p.y, q.x, q.y);
    }
    
    /**
     * @param args the command line arguments
     */
      Point p = new Point();
      Point p_inicial = new Point();
      Point p_final = new Point();
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Boton;
    private javax.swing.JButton Boton2;
    // End of variables declaration//GEN-END:variables
}
