/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package entornoventanas;

/**
 *
 * @author ivan
 */
public class VentanaPrincipal extends javax.swing.JFrame {

    /**
     * Creates new form VentanaPrincipal
     */
    public VentanaPrincipal() {
        initComponents();
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Escritorio = new javax.swing.JDesktopPane();
        jMenuBar1 = new javax.swing.JMenuBar();
        menuArchivo = new javax.swing.JMenu();
        nuevaVentanaMenu = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().add(Escritorio, java.awt.BorderLayout.CENTER);

        menuArchivo.setText("Archivo");

        nuevaVentanaMenu.setText("Nueva ");
        nuevaVentanaMenu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nuevaVentanaMenuActionPerformed(evt);
            }
        });
        menuArchivo.add(nuevaVentanaMenu);

        jMenuBar1.add(menuArchivo);

        setJMenuBar(jMenuBar1);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void nuevaVentanaMenuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nuevaVentanaMenuActionPerformed
        VentanaInerna nuevaVentana = new VentanaInerna();
        this.Escritorio.add(nuevaVentana);
        nuevaVentana.setVisible(true);
    }//GEN-LAST:event_nuevaVentanaMenuActionPerformed

    /**
     * @param args the command line arguments
     */
   
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JDesktopPane Escritorio;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenu menuArchivo;
    private javax.swing.JMenuItem nuevaVentanaMenu;
    // End of variables declaration//GEN-END:variables
}
